--
-- PostgreSQL database dump
--

\restrict 8qiOkICNuUrBMQuDmsORMLPN0KPmZPWcemv7VSmKcPTOWNldmMhnKvac35uOaFa

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Activity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Activity" (
    activity_id bigint NOT NULL,
    creator_id bigint NOT NULL,
    chat_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    event_time timestamp without time zone NOT NULL,
    is_cancelled boolean
);


--
-- Name: Activity_Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Activity_Users" (
    activity_id bigint NOT NULL,
    user_id bigint NOT NULL,
    joined_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: Activity_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Activity_activity_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Activity_activity_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Activity_activity_id_seq" OWNED BY public."Activity".activity_id;


--
-- Name: Chat_Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Chat_Users" (
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL,
    joined_at timestamp without time zone DEFAULT now() NOT NULL,
    id bigint NOT NULL
);


--
-- Name: Chat_Users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Chat_Users" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Chat_Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Chats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Chats" (
    chat_id bigint NOT NULL,
    name character varying(255),
    is_group boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: Chats_chat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Chats_chat_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Chats_chat_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Chats_chat_id_seq" OWNED BY public."Chats".chat_id;


--
-- Name: Friendships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Friendships" (
    friendship_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    receiver_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: Friendships_friendship_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Friendships_friendship_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Friendships_friendship_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Friendships_friendship_id_seq" OWNED BY public."Friendships".friendship_id;


--
-- Name: Message_Seen; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Message_Seen" (
    id bigint NOT NULL,
    message_id bigint NOT NULL,
    user_id bigint NOT NULL,
    seen_at timestamp without time zone DEFAULT now()
);


--
-- Name: Message_Seen_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Message_Seen_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Message_Seen_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Message_Seen_id_seq" OWNED BY public."Message_Seen".id;


--
-- Name: Messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Messages" (
    message_id bigint NOT NULL,
    chat_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    content character varying(255) NOT NULL,
    status character varying(255) DEFAULT 'sending'::character varying NOT NULL,
    sent_at timestamp without time zone DEFAULT now() NOT NULL,
    reply_to_message_id bigint,
    reply_preview character varying(255),
    reply_sender_name character varying(255),
    CONSTRAINT "Messages_status_check" CHECK (((status)::text = ANY (ARRAY[('sending'::character varying)::text, ('sent'::character varying)::text, ('seen'::character varying)::text])))
);


--
-- Name: Messages_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Messages_message_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Messages_message_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Messages_message_id_seq" OWNED BY public."Messages".message_id;


--
-- Name: User_Images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."User_Images" (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    image_path character varying(255) NOT NULL
);


--
-- Name: User_Images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."User_Images_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: User_Images_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."User_Images_id_seq" OWNED BY public."User_Images".id;


--
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    country_of_origin character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    profile_image_id bigint,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    bio character varying(1000)
);


--
-- Name: Users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Users_id_seq" OWNED BY public."Users".id;


--
-- Name: chat_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_users (
    id bigint NOT NULL,
    chat_id bigint,
    joined_at timestamp(6) without time zone,
    user_id bigint
);


--
-- Name: chat_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Activity activity_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity" ALTER COLUMN activity_id SET DEFAULT nextval('public."Activity_activity_id_seq"'::regclass);


--
-- Name: Chats chat_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chats" ALTER COLUMN chat_id SET DEFAULT nextval('public."Chats_chat_id_seq"'::regclass);


--
-- Name: Friendships friendship_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Friendships" ALTER COLUMN friendship_id SET DEFAULT nextval('public."Friendships_friendship_id_seq"'::regclass);


--
-- Name: Message_Seen id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Message_Seen" ALTER COLUMN id SET DEFAULT nextval('public."Message_Seen_id_seq"'::regclass);


--
-- Name: Messages message_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages" ALTER COLUMN message_id SET DEFAULT nextval('public."Messages_message_id_seq"'::regclass);


--
-- Name: User_Images id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User_Images" ALTER COLUMN id SET DEFAULT nextval('public."User_Images_id_seq"'::regclass);


--
-- Name: Users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users" ALTER COLUMN id SET DEFAULT nextval('public."Users_id_seq"'::regclass);


--
-- Name: Activity_Users Activity_Users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity_Users"
    ADD CONSTRAINT "Activity_Users_pkey" PRIMARY KEY (activity_id, user_id);


--
-- Name: Activity Activity_chat_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity"
    ADD CONSTRAINT "Activity_chat_id_key" UNIQUE (chat_id);


--
-- Name: Activity Activity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity"
    ADD CONSTRAINT "Activity_pkey" PRIMARY KEY (activity_id);


--
-- Name: Chat_Users Chat_Users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chat_Users"
    ADD CONSTRAINT "Chat_Users_pkey" PRIMARY KEY (chat_id, user_id);


--
-- Name: Chats Chats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chats"
    ADD CONSTRAINT "Chats_pkey" PRIMARY KEY (chat_id);


--
-- Name: Friendships Friendships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Friendships"
    ADD CONSTRAINT "Friendships_pkey" PRIMARY KEY (friendship_id);


--
-- Name: Message_Seen Message_Seen_message_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Message_Seen"
    ADD CONSTRAINT "Message_Seen_message_id_user_id_key" UNIQUE (message_id, user_id);


--
-- Name: Message_Seen Message_Seen_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Message_Seen"
    ADD CONSTRAINT "Message_Seen_pkey" PRIMARY KEY (id);


--
-- Name: Messages Messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT "Messages_pkey" PRIMARY KEY (message_id);


--
-- Name: User_Images User_Images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User_Images"
    ADD CONSTRAINT "User_Images_pkey" PRIMARY KEY (id);


--
-- Name: Users Users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_email_key" UNIQUE (email);


--
-- Name: Users Users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id);


--
-- Name: chat_users chat_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_users
    ADD CONSTRAINT chat_users_pkey PRIMARY KEY (id);


--
-- Name: User_Images unique_user_image; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User_Images"
    ADD CONSTRAINT unique_user_image UNIQUE (user_id, image_path);


--
-- Name: Friendships Friendships_receiver_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Friendships"
    ADD CONSTRAINT "Friendships_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES public."Users"(id) ON DELETE CASCADE;


--
-- Name: Friendships Friendships_sender_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Friendships"
    ADD CONSTRAINT "Friendships_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES public."Users"(id) ON DELETE CASCADE;


--
-- Name: Message_Seen Message_Seen_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Message_Seen"
    ADD CONSTRAINT "Message_Seen_message_id_fkey" FOREIGN KEY (message_id) REFERENCES public."Messages"(message_id);


--
-- Name: Message_Seen Message_Seen_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Message_Seen"
    ADD CONSTRAINT "Message_Seen_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- Name: Activity activity_chat_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity"
    ADD CONSTRAINT activity_chat_id_foreign FOREIGN KEY (chat_id) REFERENCES public."Chats"(chat_id);


--
-- Name: Activity activity_creator_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity"
    ADD CONSTRAINT activity_creator_id_foreign FOREIGN KEY (creator_id) REFERENCES public."Users"(id);


--
-- Name: Activity_Users activity_users_activity_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity_Users"
    ADD CONSTRAINT activity_users_activity_id_foreign FOREIGN KEY (activity_id) REFERENCES public."Activity"(activity_id);


--
-- Name: Activity_Users activity_users_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activity_Users"
    ADD CONSTRAINT activity_users_user_id_foreign FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- Name: Chat_Users chat_users_chat_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chat_Users"
    ADD CONSTRAINT chat_users_chat_id_foreign FOREIGN KEY (chat_id) REFERENCES public."Chats"(chat_id);


--
-- Name: Chat_Users chat_users_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chat_Users"
    ADD CONSTRAINT chat_users_user_id_foreign FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- Name: Messages messages_chat_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT messages_chat_id_foreign FOREIGN KEY (chat_id) REFERENCES public."Chats"(chat_id);


--
-- Name: Messages messages_sender_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT messages_sender_id_foreign FOREIGN KEY (sender_id) REFERENCES public."Users"(id);


--
-- Name: User_Images user_images_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User_Images"
    ADD CONSTRAINT user_images_user_id_foreign FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- Name: Users users_profile_image_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT users_profile_image_id_foreign FOREIGN KEY (profile_image_id) REFERENCES public."User_Images"(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict 8qiOkICNuUrBMQuDmsORMLPN0KPmZPWcemv7VSmKcPTOWNldmMhnKvac35uOaFa

