spring.application.name=springbackend
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

spring.datasource.url=jdbc:postgresql://localhost:5432/mobile_app
spring.datasource.username=postgres
spring.datasource.password=12345678

jwt.secret=jwt.secret=8ef7c48c6d06d6637f36d3afc35d0c0c76b2579c08b7d5304b9d22dd1dbfa8dd3fc10eb6f53bc47e5db8f08c0864cde1
jwt.access-expiration=900000
jwt.refresh-expiration=2592000000

server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true